database_creds:
    db_username: ENC[AES256_GCM,data:BebcohfeawTHRyBDUA==,iv:y/t1xZ8sHvZnzJfhUzi4y9366idvuvktCFgTHcY19g8=,tag:a/gyPh+Z3KtNTN6Zyv72MA==,type:str]
    db_password: ENC[AES256_GCM,data:trHXg6RG0KMV,iv:Kzy6ZTviB70ZtMJeTPUZPgbqpz3Xb2hbdQ0oFd9ontM=,tag:vtlrjbqjQ+f6c0IRCRhesw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-20T20:53:42Z"
    mac: ENC[AES256_GCM,data:wx3QkoMaSu1Fysci/XB8MNqJUTqh3P/QlJDN2WeSAxYf/gCpd1Fqw7+wNMThCc8zHre0ajbMCLjQQ4oUpxE64YTMwWHB7dvvhbArr3S7dLfDCBtdEKMXLRKXdKZlE17ru/Gi5Uz0CoF42nEsB9gwHNc0ATROma6jdAf3XR2DZPM=,iv:4gwQlCntfcU9mQoKJtaNaPml8U1MXX6eRXOgCNtWsYA=,tag:W/KYiwsaFohRB2jhiI2Yjw==,type:str]
    pgp:
        - created_at: "2022-12-17T19:29:57Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA5UwyPHWzUaUAQwAizDn9mYT+C6dEZpd2xPzS1uLHB1LqLn6KAKYBHdOdvkX
            Sbcrcx/OiqkRHsTDq9cG2mrzmvfNHghC1GQuouA7D5EB6Hi5bo2JN2dgkq/LR9yf
            Q48y1FJ3SMQn0tQImoIJORtTrNYI/KaJHxGXG/fxKLWzCjRYJBtEUQSCkHpdfWYb
            mNYiTF0zsMxfFRrzY06VGKA6W6NoDaPACBaozIx/ayRSnWGLFw9i2ZEv6vkQ1DGW
            Z+vEBsNxwodtpPJHXExpchoyuKvAMEM+3OJOrOloSV/UbI/S42hITFNI8wzkIiYL
            lP178Me2aAwA7Cgbd1zQyEAmr0fmrggKpHPwU9db6lxC1VGHbyPX1brc9LryR3iL
            O8XDzz2EaMP13tqhZ/eHZl37jo/uZbU14/LPE2EZd7rvgbKBdSpqVj2FxxoWZgg4
            QG08oFea1LbnXPx7NjcwBZfUaZXHgjXmPykx1kQOE3bU4iSNKeoYcxZJesoBTffc
            5BPbXkyAvIEexwnD+KiG1GgBCQIQsLfEBJPuiAXcCs2Rbe9wNZuEboBuOPpNxpjE
            Xl89sB3QinUZsd+Ooa9ELehE131JM42kcYmsPp+7zwidmjmLtlgsGeDpTNH0VqLu
            hUpxEvYshREHrTSMlCOI72XKRc/NxVS7JQ==
            =+EFp
            -----END PGP MESSAGE-----
          fp: 9C67158A681222C1AF4201B66A61185636929DF1
    unencrypted_suffix: _unencrypted
    version: 3.7.3
