env: dev

cognito:
  cognito_user_pool_id: us-east-1_NPkEWApKK
  cognito_user_pool_client_id: d60f1vmjvj3f6t5d2dd13qcp

vpc:
  vpc_id: vpc-02f095d0f227d189d
  lambda_security_group: sg-083c912971637ce4e
  public_1_id: subnet-05b8c72980911958b
  public_2_id: subnet-06b9c3eb6519cd18c
  private_1_id: subnet-01e08da753e0ea9d3
  private_2_id: subnet-0723cb873b3e183a8

parameters:
  db_username_ssm_parameter_arn: /home-chef/dev/db-username
  db_password_ssm_parameter_arn: /home-chef/dev/db-password
  es_username_ssm_parameter_arn: /home-chef/dev/es-username
  es_password_ssm_parameter_arn: /home-chef/dev/es-password
  db_host: home-chef-dev.cns7xbkyh0nk.us-east-1.rds.amazonaws.com
  db_name: homechef
